### ISSUE TITLE
Example of using SRD, restdocs-openapi and restdocs-spec

### ISSUE THREAD

**Issue by Cepr0** [BerkleyTechnologyServices/restdocs-spec#13]
Could you please provide a basic example of using 'Spring REST Docs', 'restdocs-openapi' and 'restdocs-spec'?
Thanks in advance.

**Comment by klieber** [comment]
Yes, this is coming.  Still working on getting a few more issues figured out integrating restdocs-openapi with restdocs-spec.  Very close though, so it should be coming soon.

**Comment by klieber** [comment]
@Cepr0 here is the sample project: https://github.com/BerkleyTechnologyServices/restdocs-spec-example

It's still not deployed to maven central so you will have to add the [JitPack](https://jitpack.io/) repository in order to use it.  I will get it in there eventually.

Let me know how things go for you.
